name: McMmoView
main: com.handy.mcmmo.McMmoView
version: 1.0.1
author: handy
api-version: "1.13"
depend: [ mcMMO ]
description: mcMMO可视化gui
commands:
  mcmmoview:
    description: §amcMMO可视化gui
    aliases: [ mmv ]
permissions:
  mcmmoview.*:
    description: §amcMMO可视化gui
    children:
      mcmmoview.reload: true
      mcmmoview.open: true
  mcmmoview.reload:
    description: §a重新加载配置
    default: op
  mcmmoview.open:
    description: §a打开
    default: true